In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('/content/market_comments_en_first30.csv')
df

,item_category,item_id,brand,user_id,date,comment,rating,tonality
0,401,4010201,826,2217,2013-06-28,Worked for 2.5 years and that's it... it's tir...,2.0,negative
1,403,4030101,1425,1026,2010-07-04,"Two months after the warranty expired, the mac...",2.0,negative
2,401,4010401,124,2769,2010-05-27,I've been using it for three weeks. No complai...,4.0,positive
3,203,2030301,93,508,2016-10-11,"Guys, will this system unit be suitable for pl...",5.0,positive
4,205,2050201,656,1049,2010-02-26,I think the Yaris is a wonderful phone! It's p...,5.0,positive
5,405,4050102,829,576,2014-05-21,Bought 2 of these fans today! Terrible. The sp...,1.0,negative
6,203,2030201,995,2656,2010-02-27,They brought the laptop; the build quality and...,5.0,positive
7,404,4040203,759,1405,2015-01-16,"Bought this humidifier. It's noisy, and the ba...",2.0,negative
8,406,4060101,48,1538,2010-08-06,The food processor is excellent. I've been usi...,5.0,positive
9,412,4120101,11,7,2012-07-23,Excellent appliance. The auto shut-off is just...,5.0,positive
10,406,4060301,62,2170,2013-02-18,We looked at this model in the store today; at...,1.0,negative
11,407,4070101,80,1058,2012-12-15,I've used it for over a year; the oven heated ...,2.0,negative
12,404,4040204,879,1217,2012-05-28,My wife and I have been using it for several m...,5.0,positive
13,410,4100301,48,161,2017-01-19,"high speed, low noise, acceptable price, high ...",4.7,positive
14,304,3040304,1,282,2012-06-04,I was given a PSP for my birthday when I turne...,5.0,positive
15,405,4050102,617,1565,2016-04-26,"I've used it for a week, no complaints. Assemb...",5.0,positive
16,207,2070202,1008,278,2009-10-05,"If they sold you junk, there's no need to slan...",5.0,positive
17,516,5160401,109,2151,2009-10-27,"Terrible, poor-quality build; I got one with a...",1.0,negative
18,207,2070202,11,783,2009-08-31,A huge minus - no radio. Otherwise it would ha...,4.0,positive
19,107,1070902,10,1254,2010-12-25,A wonderful TV!!! Picture quality is top-notch...,5.0,positive
20,107,1070908,80,2957,2011-06-02,"The plasma is super for the price, quality is ...",5.0,positive
21,207,2070202,11,28,2010-03-07,"I'll tell a story, you decide whether to buy o...",4.0,positive
22,401,4010301,53,2217,2012-02-15,Bought 2 months ago. Before buying I had exper...,4.0,positive
23,401,4010101,863,1983,2010-12-23,Overall not a bad gas hob. The surface is mode...,4.0,positive
24,406,4060301,62,3172,2011-08-16,We bought it more than 2 years ago as a gift f...,5.0,positive
25,406,4061101,86,1538,2011-12-22,Today my husband and I bought an electric can ...,5.0,positive
26,411,4110101,13,767,2012-11-02,"A disgusting vacuum cleaner, we'd have been be...",1.0,negative
27,411,4110102,617,443,2011-07-04,I've been using this vacuum cleaner for over e...,4.0,positive
28,401,4010301,81,974,2011-12-25,"Bought it 3 days ago, today I put it to the te...",5.0,positive
29,205,2050201,318,2656,2009-08-17,"Simply super! Relatively thin, with big keys, ...",5.0,positive

In [3]:
df.describe()

       item_category       item_id        brand      user_id     rating
count      30.000000  3.000000e+01    30.000000    30.000000  30.000000
mean      339.066667  3.390952e+06   359.166667  1380.166667   3.856667
std       109.729113  1.097208e+06   415.266436   930.956537   1.518548
min       107.000000  1.070902e+06     1.000000     7.000000   1.000000
25%       207.000000  2.070202e+06    49.250000   623.750000   2.500000
50%       402.000000  4.020251e+06    89.500000  1235.500000   4.850000
75%       406.000000  4.060301e+06   733.250000  2165.250000   5.000000
max       516.000000  5.160401e+06  1425.000000  3172.000000   5.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item_category  30 non-null     int64
 1   item_id        30 non-null     int64
 2   brand          30 non-null     int64
 3   user_id        30 non-null     int64
 4   date           30 non-null     object
 5   comment        30 non-null     object
 6   rating         30 non-null     float64
 7   tonality       30 non-null     object
dtypes: float64(1), int64(4), object(3)
memory usage: 2.0+ KB

In [5]:
df.isnull().sum()

item_category    0
item_id          0
brand            0
user_id          0
date             0
comment          0
rating           0
tonality         0
dtype: int64

In [6]:
df.duplicated().sum()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [9]:
df.head()

,item_category,item_id,brand,user_id,date,comment,rating,tonality
0,401,4010201,826,2217,2013-06-28,Worked for 2.5 years and that's it... it's tir...,2.0,negative
1,403,4030101,1425,1026,2010-07-04,"Two months after the warranty expired, the mac...",2.0,negative
2,401,4010401,124,2769,2010-05-27,I've been using it for three weeks. No complai...,4.0,positive
3,203,2030301,93,508,2016-10-11,"Guys, will this system unit be suitable for pl...",5.0,positive
4,205,2050201,656,1049,2010-02-26,I think the Yaris is a wonderful phone! It's p...,5.0,positive

In [10]:
df.tail()

,item_category,item_id,brand,user_id,date,comment,rating,tonality
25,406,4061101,86,1538,2011-12-22,Today my husband and I bought an electric can ...,5.0,positive
26,411,4110101,13,767,2012-11-02,"A disgusting vacuum cleaner, we'd have been be...",1.0,negative
27,411,4110102,617,443,2011-07-04,I've been using this vacuum cleaner for over e...,4.0,positive
28,401,4010301,81,974,2011-12-25,"Bought it 3 days ago, today I put it to the te...",5.0,positive
29,205,2050201,318,2656,2009-08-17,"Simply super! Relatively thin, with big keys, ...",5.0,positive

In [11]:
df.columns

Index(['item_category', 'item_id', 'brand', 'user_id', 'date', 'comment',
       'rating', 'tonality'],
      dtype='object')

In [12]:
x=df[['comment','brand']]
y=df['tonality']


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
l=LabelEncoder()
y=l.fit_transform(y)

In [14]:
vectrizor=CountVectorizer()
x=vectrizor.fit_transform(x_train)

In [15]:
x_train_vec = vectrizor.fit_transform(x_train['comment'])


model = MultinomialNB()
model.fit(x_train_vec, y_train)

MultinomialNB()

In [16]:
acc=model.score(x_train_vec,y_train)
acc

1.0

In [17]:
a=vectrizor.transform(x_test['comment'])
y_pred=model.predict(a)

In [ ]:
user = input("Enter the comment: ")
test = vectrizor.transform([user])

prediction = model.predict(test)

print("Predicted Tonality is:", prediction[0])